apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elk
spec:
  version: 7.14.1
  count: 1
  elasticsearchRef:
    name: es
  http:
    service:
      spec:
        type: NodePort
        ports:
          - port: 5601
    tls:
      selfSignedCertificate:
        disabled: true

